create table adresa (id integer not null, city varchar(255), country varchar(255), street varchar(255), location_id integer, orders_id integer, primary key (id)) engine=InnoDB;
create table category (product_category_id integer not null, description varchar(255), name varchar(255), primary key (product_category_id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table location (id integer not null, name varchar(255), primary key (id)) engine=InnoDB;
create table order_detail (id integer not null, quantity integer, orders_id integer, primary key (id)) engine=InnoDB;
create table orders (id integer not null, created_at datetime, shipped_from_id integer, user_user_id integer, primary key (id)) engine=InnoDB;
create table product (product_id integer not null, description varchar(255), image varchar(255), name varchar(255), price decimal(19,2), weight double precision, order_detail_id integer, product_category_product_category_id integer, primary key (product_id)) engine=InnoDB;
create table revenue (id integer not null, local_date datetime, sum decimal(19,2), location_id integer, primary key (id)) engine=InnoDB;
create table roles (role_id integer not null, role_name varchar(255), primary key (role_id)) engine=InnoDB;
create table stock (id integer not null, quantity integer, location_id integer, product_product_id integer, primary key (id)) engine=InnoDB;
create table user (user_id integer not null, email_address varchar(255), fist_name varchar(255), last_name varchar(255), password varchar(255), username varchar(255), role_role_id integer, primary key (user_id)) engine=InnoDB;
alter table adresa add constraint FK_location_id_adresa foreign key (location_id) references location (id);
alter table adresa add constraint FK_orders_id_adresa foreign key (orders_id) references orders (id);
alter table order_detail add constraint FK_orders_id_orders_detail foreign key (orders_id) references orders (id);
alter table orders add constraint FK_shipped_from_id_orders foreign key (shipped_from_id) references location (id);
alter table orders add constraint FK_user_id_orders foreign key (user_user_id) references user (user_id);
alter table product add constraint FK_orders_detail_product foreign key (order_detail_id) references order_detail (id);
alter table product add constraint FK_product_category_product foreign key (product_category_product_category_id) references category (product_category_id);
alter table revenue add constraint FK_location_id_revenue foreign key (location_id) references location (id);
alter table stock add constraint FK_location_id_stock foreign key (location_id) references location (id);
alter table stock add constraint FK_product_id_stock foreign key (product_product_id) references product (product_id);
alter table user add constraint FK_role_id_user foreign key (role_role_id) references roles (role_id);
