insert into address_ (id, city, country, street) values (1, 'Watuagung', 'Indonesia', '5 Meadow Valley Point');
insert into address_ (id, city, country, street) values (2, 'Ibirataia', 'Brazil', '86 Holy Cross Avenue');
insert into address_ (id, city, country, street) values (3, 'Bayt Ta‘mar', 'Palestinian Territory', '395 Ronald Regan Avenue');
insert into address_ (id, city, country, street) values (4, 'Borek', 'Poland', '45808 Vahlen Street');
insert into address_ (id, city, country, street) values (5, 'Mouzáki', 'Greece', '871 Bunker Hill Alley');
insert into address_ (id, city, country, street) values (6, 'Nangong', 'China', '662 Sherman Street');
insert into address_ (id, city, country, street) values (7, 'Mandalgovi', 'Mongolia', '43025 Kenwood Plaza');
insert into address_ (id, city, country, street) values (8, 'Bunog', 'Philippines', '269 Laurel Street');
insert into address_ (id, city, country, street) values (9, 'Jinji', 'China', '7834 Susan Pass');
insert into address_ (id, city, country, street) values (10, 'Sobotín', 'Czech Republic', '30 Erie Hill');
insert into address_ (id, city, country, street) values (11, 'Kabin Buri', 'Thailand', '652 Sheridan Pass');
insert into address_ (id, city, country, street) values (12, 'Buenos Aires', 'Peru', '731 Dwight Pass');
insert into address_ (id, city, country, street) values (13, 'Nezvěstice', 'Czech Republic', '6503 Parkside Circle');
insert into address_ (id, city, country, street) values (14, 'Paraíso', 'Portugal', '65706 Katie Point');
insert into address_ (id, city, country, street) values (15, 'Ngadri', 'Indonesia', '009 Moose Alley');
insert into address_ (id, city, country, street) values (16, 'Kasama', 'Japan', '0 Arrowood Lane');
insert into address_ (id, city, country, street) values (17, 'Khorramdarreh', 'Iran', '81 Monument Point');
insert into address_ (id, city, country, street) values (18, 'Cassilândia', 'Brazil', '548 Debra Terrace');
insert into address_ (id, city, country, street) values (19, 'Jebba', 'Nigeria', '6483 Daystar Trail');
insert into address_ (id, city, country, street) values (20, 'Emiliano Zapata', 'Mexico', '14 Southridge Alley');

insert into location (id, name, address_id) values (1, 'Kwinu', 1);
insert into location (id, name, address_id) values (2, 'Zoomzone', 2);
insert into location (id, name, address_id) values (3, 'Bluejam', 3);
insert into location (id, name, address_id) values (4, 'Yata', 4);
insert into location (id, name, address_id) values (5, 'Fivebridge', 5);
insert into location (id, name, address_id) values (6, 'Yakijo', 6);
insert into location (id, name, address_id) values (7, 'Avamm', 7);
insert into location (id, name, address_id) values (8, 'Pixoboo', 8);
insert into location (id, name, address_id) values (9, 'Photojam', 9);
insert into location (id, name, address_id) values (10, 'Zoomdog', 10);
insert into location (id, name, address_id) values (11, 'Devshare', 11);
insert into location (id, name, address_id) values (12, 'Wordpedia', 12);
insert into location (id, name, address_id) values (13, 'Gabtune', 13);
insert into location (id, name, address_id) values (14, 'Viva', 14);
insert into location (id, name, address_id) values (15, 'Meeveo', 15);
insert into location (id, name, address_id) values (16, 'Zoomdog', 16);
insert into location (id, name, address_id) values (17, 'Jayo', 17);
insert into location (id, name, address_id) values (18, 'Janyx', 18);
insert into location (id, name, address_id) values (19, 'Realbuzz', 19);
insert into location (id, name, address_id) values (20, 'Shufflebeat', 20);
